---

variables:
  ANSIBLE_GALAXY_PACKAGE_NAME: phpipam_scan_agent
  MY_PROJECT_ID: "51640029"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/ansible_collection_kubernetes.git"
  PAGES_ENVIRONMENT_PATH: projects/ansible/collection/kubernetes/
  RELEASE_ADDITIONAL_ACTIONS_BUMP: ./.gitlab/additional_actions_bump.sh


include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - conventional_commits/.gitlab-ci.yml
      - template/ansible-collection.gitlab-ci.yaml
      - template/mkdocs-documentation.gitlab-ci.yaml
      # ToDo: update gitlabCI jobs for collections workflow
      - git_push_mirror/.gitlab-ci.yml
      - automation/.gitlab-ci-ansible.yaml


Update Git Submodules:
  extends: .ansible_playbook_git_submodule


Github (Push --mirror):
  extends:
    - .git_push_mirror
  needs: []


Website.Submodule.Deploy:
  extends: .submodule_update_trigger
  variables:
    SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/infrastructure/website
  environment:
    url: https://nofusscomputing.com/$PAGES_ENVIRONMENT_PATH
    name: Documentation
  rules:
    - if:  # condition_dev_branch_push
        $CI_COMMIT_BRANCH == "development" && 
        $CI_PIPELINE_SOURCE == "push"
      exists:
        - '{docs/**,pages/**}/*.md'
      changes:
        paths:
          - '{docs/**,pages/**}/*.md'
        compare_to: 'master'
      when: always

    - when: never
