INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Kubernetes Ansible Collection
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/collections/kubernetes
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/collections/kubernetes/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - projects/ansible/index.md

    - Execution Environment:

      - projects/ansible/execution_environment/index.md

    - Playbooks:

      - projects/ansible/playbooks/index.md

    - Collections:

      - projects/ansible/collection/index.md

      - Kubernetes:

        - projects/ansible/collection/kubernetes/index.md

        - Role nfc_kubernetes:

          - projects/ansible/collection/kubernetes/roles/nfc_kubernetes/index.md

          - projects/ansible/collection/kubernetes/roles/nfc_kubernetes/ansible.md

          - projects/ansible/collection/kubernetes/roles/nfc_kubernetes/firewall.md

          - projects/ansible/collection/kubernetes/roles/nfc_kubernetes/rbac.md

          - projects/ansible/collection/kubernetes/roles/nfc_kubernetes/release_notes.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

