---

- name: Restart Kubernetes
  ansible.builtin.service:
    name: |-
      {%- if nfc_role_kubernetes_master | default(false) | bool -%}
        k3s
      {%- else -%}
        k3s-agent
      {%- endif -%}
    state: restarted
  listen: kubernetes_restart
  when: |-
    not (
      nfc_kubernetes_no_restart
        or
      (
        nfc_role_kubernetes_master
          and
        nfc_kubernetes_no_restart_master
      )
        or
      (
        inventory_hostname == kubernetes_config.cluster.prime.name | default(inventory_hostname)
          and
        nfc_kubernetes_no_restart_prime
      )
        or
      (
        nfc_role_kubernetes_worker
          and
        nfc_kubernetes_no_restart_slave
      )
    )

