---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-mutable-tag
  labels: 
    <<: {{ kubernetes_config.defaults.labels.deployment_labels | from_yaml }}
  annotations:
    ansible.kubernetes.io/path: {{ item }}
    policies.kyverno.io/title: Disallow mutable Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The ':latest', ':master' and ':dev(elopment)' tags are mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application Pod. This policy validates that the image
      specifies a tag and that it is not called `latest` `master` or`dev(elopment)`.      
spec:
  #failurePolicy: Fail
  validationFailureAction: Audit
  background: true
  rules:
  - name: require-image-tag
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "An image tag is required."
      pattern:
        spec:
          containers:
          - image: "*:*"
  - name: validate-image-tag
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Using a mutable image tag e.g. 'latest', 'master' or 'dev[elopment]' is not allowed."
      pattern:
        spec:
          containers:
          - image: "!*:[latest|master|dev|development]"
