# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: kube-metrics
#   namespace: kube-metrics
#   labels:
#     app.kubernetes.io/name: kube-metrics
#     # app.kubernetes.io/instance: { .Release.Name }}
#     # app.kubernetes.io/version: { .Chart.Version | quote }}
#     # app.kubernetes.io/managed-by: { .Release.Service }}
#     app.kubernetes.io/component: loki
#     app.kubernetes.io/part-of: metrics

# spec:
#   egress: 
#   - to:
#     #- podSelector:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: "default"
#     ports:
#     - port: 443
#       protocol: TCP
#   # ingress:
#   # - from:
#   #   #- podSelector:
#   #   - namespaceSelector:
#   #       matchLabels:
#   #         #app.kubernetes.io/name: prometheus
#   #         #app.kubernetes.io/instance: k8s
#   #         #app.kubernetes.io/managed-by: prometheus-operator
#   #         app.kubernetes.io/name: grafana-agent
#   #         #app.kubernetes.io/part-of: kube-prometheus
      
#   #     #app: grafana
#   policyTypes:
#   - Egress
#   #- Ingress
